var formulas = (function() {
	var matrix = formulaUtils.matrix;

	return {
		formula1 : "\\log_2 N",
		formula2 : "\\(x, y) + (z, t) = (x + z, y + t)",
		formula3 : "\\(x, y) \\cdot (z, t) = (xz - yt, xy + yz)",
		formula4 : "\\OM = \sqrt{(x_M - x_O)^2 + (y_M - y_O)^2}",
		formula5 : "A = " + matrix(3,3,["a_{11}","...","a_{1n}","...","...","...","a_{m1}","...","a_{mn}"]) + " = [a_{ij}]",
		formula6 : "I_n = " + matrix(4, 4,[1, 0, "...", 0, 0, 1, "...", 0, "...", "...", "...", "...", 0, 0, "...", 1]),
		formula7 : matrix(3, 1,["5 + 3i", "4 - i", "7"]),
		formula8 : matrix(6, 1, ["x_1 \\cdot" + matrix(4, 1, ["y_1", "y_2", "...", "y_m"]),"x_2 \\cdot" + matrix(4, 1, ["y_1", "y_2", "...", "y_m"]), "...","...", "...", "x_n \\cdot" + matrix(4, 1, ["y_1", "y_2", "...", "y_m"])]),
		f1 : "N",
		f2 : "log_2 N",
		f3 : "(x, y)",
		f4 : "x, y \\in \\mathbb{R}",
		f5 : "(x, y)",
		f6 : "(a, b)",
		f7 : "x = a",
		f8 : "y = b",
		f9 : "a = (x, 0)",
		f10 : "b = (y, 0)",
		f11 : "ab = (xy, 0)",
		f12 : "a = (0, x)",
		f13 : "b = (0, y)",
		f14 : "ab = (-xy, 0)",
		f15 : "\\mathbb{R}^2",
		f16 : "\\mathbb{C}",
		f17 : "z = (x, y) \\in \\mathbb{C}",
		f18 : "\\mathbb{C}^{*}",
		f19 : "\\mathbb{C} - \\{(0, 0)\\}",
		f20 : "z = (x, y)",
		f21 : "z = x + yi",
		f22 : "x, y",
		f23 : "i^2 = -1",
		f24 : "i^2 = -1",
		f25 : "i^2 = i \\cdot i = (0, 1) \\cdot (0, 1) = (-1, 0) = -1",
		f26 : "x + yi",
		f27 : "z = (x, y)",
		f28 : "\\mathbb{C} = \\{x + yi | x \\in \\mathbb{R}, y \\in \\mathbb{R}, i^2 = -1\\}",
		f29 : "z = (x, y)",
		f30 : "x + yi",
		f31 : "x = Re(z)",
		f32 : "z",
		f33 : "y = Im(z)",
		f34 : "z",
		f35 : "z = x + yi",
		f36 : "\\overline{z} = x - yi",
		f37 : "z",
		f38 : "z = \\overline{z}",
		f39 : "z",
		f40 : "z",
		f41 : "z \\cdot \\overline{z}",
		f42 : "\\overline{x + y} = \\overline{x} + \\overline{y}",
		f43 : "\\overline{x \\cdot y} = \\overline{x} \\cdot \\overline{y}",
		f44 : "z",
		f45 : "\\overline{(z^{-1})} = (\\overline{z})^{-1}",
		f46 : "\\overline{\\bigg(\\frac{x}{y}\\bigg)}=\\frac{\\overline{x}}{\\overline{y}}, y \\neq 0",
		f47 : "Re(z) = \\frac{z + \\overline{z}}{2}",
		f48 : "Im(z) = \\frac{z - \\overline{z}}{2i}",
		f49 : "z",
		f50 : "|z| = \\sqrt{x^2+y^2}",
		f51 : "z = x + yi",
		f52 : "-|z| \\leq Re(z) \\leq |z|",
		f53 : "-|z| \\leq Im(z) \\leq |z|",
		f54 : "|z| \\geq 0",
		f55 : "z",
		f56 : "|z| = 0",
		f57 : "z = 0",
	};
})();
